import NavBar from "@/components/NavBar/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./starry-night-both.css";

import BlogArchive from "@/components/BlogArchive/BlogArchive";
import Header from "@/components/Header";
import SearchBar from "@/components/SearchBar/Searchbar";
import "@/styles/global.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="mainWrapper">
          <Header />
          <NavBar archive={<BlogArchive />} />
          <div className="bottomWrapper">
            <div className="columnLeft">
              <img style={{ width: "150px" }} src="/musiclargesidebanner.gif" />
              <img style={{ width: "150px" }} src="/getpaidsmall3.gif" />
            </div>
            <div className="columnCenter">
              <main>{children}</main>
            </div>
            <div className="columnRight">
              <img src="/ericLogos/iconeric.gif"></img>
              <SearchBar />
              <BlogArchive />
              <img src="/ericLogos/eric.gif"></img>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
