import NavBar from "@/components/NavBar/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./starry-night-both.css";

import BlogArchive from "@/components/BlogArchive/BlogArchive";
import Header from "@/components/Header";
import SearchBar from "@/components/SearchBar/Searchbar";
import "@/styles/global.scss";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <div className="mainWrapper">
            <Header />
            <NavBar archive={<BlogArchive />} />
            <div className="bottomWrapper">
              <div className="columnLeft">
                <img
                  style={{ width: "150px" }}
                  src="/kevinsKillerGifs/fem_fighter.gif"
                />
                <img
                  style={{ width: "150px" }}
                  src="/kevinsKillerGifs/rat_soldier.gif"
                />
              </div>
              <div className="columnCenter">
                <main>{children}</main>
              </div>
              <div className="columnRight">
                <img src="/ericLogos/iconeric.gif"></img>
                <SearchBar />
                <BlogArchive />
                <img src="/ericLogos/eric.gif"></img>
              </div>
            </div>
          </div>
        </body>
      </html>
    </Providers>
  );
}
